name: E2E (Playwright)

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Node 環境
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      # 3) 依存をインストール（Playwright の JS 本体もここで入る）
      - run: npm ci

      # 4) Playwright ブラウザ & OS 依存ライブラリをインストール（推奨）
      - uses: microsoft/playwright-install@v1
        with:
          # オプション不要。必要なブラウザと OS パッケージを自動取得
          # cache は Action 内蔵機能で自動化されています
          # 詳細: https://github.com/microsoft/playwright-install
          check-latest: true # ← 任意: 最新 Playwright に追従したい場合

      # 5) TypeScript 型チェック
      - run: npx tsc --noEmit

      # 6) Playwright テスト（HTML レポート）
      - run: npx playwright test --reporter=html

      # 7) レポートをアーティファクト化（失敗しても必ず実行）
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      # 8) Next.js 本番ビルド（任意だが品質ゲートに有益）
      - run: npm run build
